spring.application.name="https;AccountName=samplerga0a3;AccountKey=pUzEx6rzFhayptVLVwYyCULblXZ8ua42ZQ+87I+C7uvdVIQvseUSpbj6y0NTtbu7f2V4Kn8wA7oK+AStmDtJEw==;EndpointSuffix=core.windows.net"

logging.level.root=INFO
logging.level.com.azure_batch_function=DEBUG